//! Animus Launch — the deterministic, LLM-free project bootstrapper (ADR-053).
//!
//! `scaffold()` takes a [`LaunchSpec`] and creates a new git repository at a
//! target path: `main` + `dev` branches, an initial commit, and a
//! Sprint Loops Book v2 skeleton (`docs/.sprint-loop-book`, intent, work,
//! sprint, and history records). It is **user-run, deterministic, and no LLM
//! is involved** — so `ferric-guard`'s workspace-containment (which confines
//! an *agent*) does not apply. The one real safety property is
//! **refuse-to-clobber**: never scaffold into a path that already exists and is
//! non-empty (or is not a directory). Git is invoked as a closed set of
//! subcommands via `std::process::Command` (a named subprocess boundary,
//! ADR-013), each step's exit status checked and stderr captured on failure.

use std::collections::BTreeSet;
use std::fs::OpenOptions;
use std::io::Write;
use std::path::{Path, PathBuf};
use std::process::{Command, Output};
use std::str::FromStr;

use thiserror::Error;

/// Supported project profiles.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ProjectType {
    Rust,
    Python,
    Web,
    Empty,
}

impl FromStr for ProjectType {
    type Err = String;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s.trim().to_lowercase().as_str() {
            "rust" => Ok(ProjectType::Rust),
            "python" | "py" => Ok(ProjectType::Python),
            "web" | "html" => Ok(ProjectType::Web),
            "empty" | "none" | "" => Ok(ProjectType::Empty),
            _ => Err(format!("Unknown project type: {}", s)),
        }
    }
}

/// Everything Launch needs to bootstrap a project. Built by the CLI (from flags
/// and/or an interview) and handed to [`scaffold`].
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct LaunchSpec {
    pub name: String,
    pub path: PathBuf,
    pub goal: String,
    /// A defined project-type profile to scaffold. Defaults to Empty.
    pub project_type: ProjectType,
}

/// What `scaffold` created.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ScaffoldReport {
    pub path: PathBuf,
    pub branches: Vec<String>,
    pub files_created: Vec<String>,
}

#[derive(Debug, Error)]
pub enum LaunchError {
    /// The target already exists and is non-empty, or is not a directory —
    /// refuse-to-clobber (ADR-053, the sole safety property).
    #[error("refusing to scaffold into {0}: it already exists and is not an empty directory")]
    TargetNotEmpty(PathBuf),
    #[error("invalid launch spec: {0}")]
    Invalid(String),
    #[error("git failed: {0}")]
    Git(String),
    #[error("scaffold inventory changed unexpectedly at {0}")]
    InventoryMismatch(PathBuf),
    #[error("i/o error: {0}")]
    Io(#[from] std::io::Error),
}

/// A project name is valid if it is non-empty after trimming.
pub fn validate_project_name(name: &str) -> Result<(), String> {
    if name.trim().is_empty() {
        return Err("project name must not be empty".to_string());
    }
    if name.chars().any(char::is_control) {
        return Err("project name must not contain control characters or newlines".to_string());
    }
    Ok(())
}

/// A goal is valid if it is non-empty after trimming.
pub fn validate_goal(goal: &str) -> Result<(), String> {
    if goal.trim().is_empty() {
        return Err("goal must not be empty".to_string());
    }
    if goal
        .chars()
        .any(|character| character.is_control() && !matches!(character, '\r' | '\n' | '\t'))
    {
        return Err(
            "goal must not contain control characters other than line breaks or tabs".to_string(),
        );
    }
    Ok(())
}

/// Normalize all supported line endings before deriving or rendering Book
/// content. This keeps generated bytes stable across callers and platforms.
fn normalize_newlines(text: &str) -> String {
    text.replace("\r\n", "\n").replace('\r', "\n")
}

/// Render user-controlled text as inert Markdown text. HTML entities are used
/// instead of backslash escapes so a supplied backslash cannot cancel an
/// escape. Unicode and ordinary prose punctuation remain readable.
fn escape_markdown_text(text: &str) -> String {
    let mut escaped = String::with_capacity(text.len());
    for character in text.chars() {
        match character {
            '&' => escaped.push_str("&amp;"),
            '<' => escaped.push_str("&lt;"),
            '>' => escaped.push_str("&gt;"),
            '\\' => escaped.push_str("&#92;"),
            '`' => escaped.push_str("&#96;"),
            '*' => escaped.push_str("&#42;"),
            '_' => escaped.push_str("&#95;"),
            '{' => escaped.push_str("&#123;"),
            '}' => escaped.push_str("&#125;"),
            '[' => escaped.push_str("&#91;"),
            ']' => escaped.push_str("&#93;"),
            '(' => escaped.push_str("&#40;"),
            ')' => escaped.push_str("&#41;"),
            '#' => escaped.push_str("&#35;"),
            '+' => escaped.push_str("&#43;"),
            '-' => escaped.push_str("&#45;"),
            '!' => escaped.push_str("&#33;"),
            '|' => escaped.push_str("&#124;"),
            '~' => escaped.push_str("&#126;"),
            '\t' => escaped.push_str("    "),
            _ => escaped.push(character),
        }
    }
    escaped
}

/// Render normalized user text as a Markdown quotation. Every line stays
/// inside the quotation, including blank lines, while structural punctuation
/// is escaped by [`escape_markdown_text`].
fn render_markdown_literal(text: &str) -> String {
    let normalized = normalize_newlines(text);
    normalized
        .trim()
        .split('\n')
        .map(|line| format!("> {}", escape_markdown_text(line)))
        .collect::<Vec<_>>()
        .join("\n")
}

/// Derive a Cargo-safe package identifier from a display name. Rust projects
/// accept ASCII letters, digits, `_`, `-`, and spaces (mapped to `_`). Other
/// display names remain valid for non-Rust profiles, where no Cargo identifier
/// is emitted. A prefix keeps digit/punctuation-leading names valid crate
/// identifiers as well as valid Cargo package names.
fn cargo_package_name(display_name: &str) -> Result<String, String> {
    let mut package_name = String::with_capacity(display_name.len());
    for character in display_name.trim().chars() {
        match character {
            character if character.is_ascii_alphanumeric() => {
                package_name.push(character.to_ascii_lowercase());
            }
            ' ' => package_name.push('_'),
            '_' | '-' => package_name.push(character),
            _ => {
                return Err(
                    "Rust project name must contain only ASCII letters, digits, spaces, '-' or '_'"
                        .to_string(),
                );
            }
        }
    }
    if !package_name
        .chars()
        .any(|character| character.is_ascii_alphanumeric())
    {
        return Err(
            "Rust project name must contain at least one ASCII letter or digit".to_string(),
        );
    }
    if !package_name.starts_with(|character: char| character.is_ascii_lowercase()) {
        package_name.insert_str(0, "project_");
    }
    if package_name.len() > 64 {
        return Err("derived Rust package name must not exceed 64 ASCII characters".to_string());
    }
    // `src/main.rs` makes the package name an implicit binary target. Keep
    // these sets aligned with Cargo's `restricted_names` checks for artifact
    // directory conflicts and cross-platform Windows filenames.
    if ["deps", "examples", "build", "incremental"].contains(&package_name.as_str()) {
        return Err(format!(
            "derived Rust package name `{package_name}` conflicts with Cargo's build directories"
        ));
    }
    if [
        "con", "prn", "aux", "nul", "com1", "com2", "com3", "com4", "com5", "com6", "com7", "com8",
        "com9", "lpt1", "lpt2", "lpt3", "lpt4", "lpt5", "lpt6", "lpt7", "lpt8", "lpt9",
    ]
    .contains(&package_name.as_str())
    {
        return Err(format!(
            "derived Rust package name `{package_name}` is a reserved Windows filename"
        ));
    }
    Ok(package_name)
}

/// Derive a few seed backlog bullets from the goal (echoing GECK's
/// `_derive_initial_tasks`/`_parse_goal_to_bullets`). Splits the goal on
/// sentence/clause separators; always returns at least one task. Pure.
pub fn derive_initial_tasks(goal: &str) -> Vec<String> {
    let normalized = normalize_newlines(goal);
    let clauses: Vec<String> = normalized
        .split(['.', ';', ',', '\n'])
        .map(str::trim)
        .filter(|c| !c.is_empty())
        .map(|c| {
            // Capitalize the first character for a task-like reading.
            let mut chars = c.chars();
            match chars.next() {
                Some(first) => first.to_uppercase().collect::<String>() + chars.as_str(),
                None => String::new(),
            }
        })
        .collect();
    if clauses.is_empty() {
        // A goal with no clause separators becomes one task.
        return vec![format!("Implement: {}", normalized.trim())];
    }
    clauses
}

/// Is `path` a safe scaffold target? Safe iff it does not exist, or it exists
/// as a directory that is empty (hidden entries like `.git`/`.DS_Store` COUNT
/// as non-empty — the stricter, safer rule). A path that exists but is not a
/// directory is NOT safe.
fn target_is_clobber_safe(path: &Path) -> Result<bool, std::io::Error> {
    let metadata = match std::fs::symlink_metadata(path) {
        Ok(metadata) => metadata,
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => return Ok(true),
        Err(error) => return Err(error),
    };
    if metadata.file_type().is_symlink() || !metadata.is_dir() {
        return Ok(false);
    }
    // Directory: empty iff it yields no entries at all.
    Ok(path.read_dir()?.next().transpose()?.is_none())
}

/// Reserve an absent target with an atomic `create_dir`. An already-existing
/// empty directory remains supported, but is revalidated immediately before
/// scaffold creation. If an absent target appears during reservation, fail
/// closed rather than treating the racing directory as ours.
fn reserve_target(path: &Path) -> Result<(), LaunchError> {
    match std::fs::symlink_metadata(path) {
        Ok(_) => {
            if target_is_clobber_safe(path)? {
                Ok(())
            } else {
                Err(LaunchError::TargetNotEmpty(path.to_path_buf()))
            }
        }
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => {
            if let Some(parent) = path
                .parent()
                .filter(|parent| !parent.as_os_str().is_empty())
            {
                std::fs::create_dir_all(parent)?;
            }
            match std::fs::create_dir(path) {
                Ok(()) => Ok(()),
                Err(error) if error.kind() == std::io::ErrorKind::AlreadyExists => {
                    Err(LaunchError::TargetNotEmpty(path.to_path_buf()))
                }
                Err(error) => Err(LaunchError::Io(error)),
            }
        }
        Err(error) => Err(LaunchError::Io(error)),
    }
}

/// Create one scaffold-owned directory. Any pre-existing node indicates that
/// content appeared after target reservation, so it is never reused.
fn create_scaffold_dir(root: &Path, relative: &str) -> Result<(), LaunchError> {
    let path = root.join(relative);
    match std::fs::create_dir(&path) {
        Ok(()) => Ok(()),
        Err(error) if error.kind() == std::io::ErrorKind::AlreadyExists => {
            Err(LaunchError::TargetNotEmpty(root.to_path_buf()))
        }
        Err(error) => Err(LaunchError::Io(error)),
    }
}

/// Write one known scaffold file with OS-level exclusive creation. A racing
/// file, directory, or symlink can therefore never be overwritten.
fn write_scaffold_file(
    root: &Path,
    relative: &str,
    contents: impl AsRef<[u8]>,
) -> Result<(), LaunchError> {
    let path = root.join(relative);
    let mut file = match OpenOptions::new().write(true).create_new(true).open(&path) {
        Ok(file) => file,
        Err(_error) if std::fs::symlink_metadata(&path).is_ok() => {
            return Err(LaunchError::TargetNotEmpty(root.to_path_buf()));
        }
        Err(error) => return Err(LaunchError::Io(error)),
    };
    file.write_all(contents.as_ref())?;
    file.sync_all()?;
    Ok(())
}

fn collect_scaffold_tree(
    root: &Path,
    directory: &Path,
    files: &mut BTreeSet<PathBuf>,
    directories: &mut BTreeSet<PathBuf>,
) -> Result<(), LaunchError> {
    for entry in std::fs::read_dir(directory)? {
        let entry = entry?;
        let path = entry.path();
        let relative = path
            .strip_prefix(root)
            .map_err(|_| LaunchError::InventoryMismatch(root.to_path_buf()))?
            .to_path_buf();
        let file_type = entry.file_type()?;
        if relative == Path::new(".git") {
            if !file_type.is_dir() || file_type.is_symlink() {
                return Err(LaunchError::InventoryMismatch(root.to_path_buf()));
            }
            continue;
        }
        if file_type.is_symlink() {
            return Err(LaunchError::InventoryMismatch(root.to_path_buf()));
        }
        if file_type.is_dir() {
            directories.insert(relative);
            collect_scaffold_tree(root, &path, files, directories)?;
        } else if file_type.is_file() {
            files.insert(relative);
        } else {
            return Err(LaunchError::InventoryMismatch(root.to_path_buf()));
        }
    }
    Ok(())
}

/// Require the complete non-Git filesystem tree to match the generated file
/// inventory, including the implied parent directories. This catches
/// unrelated content that appears while an existing empty target is being
/// scaffolded.
fn verify_scaffold_inventory(root: &Path, expected_files: &[String]) -> Result<(), LaunchError> {
    let expected_files: BTreeSet<PathBuf> = expected_files.iter().map(PathBuf::from).collect();
    let mut expected_directories = BTreeSet::new();
    for file in &expected_files {
        let mut parent = file.parent();
        while let Some(directory) = parent {
            if directory.as_os_str().is_empty() {
                break;
            }
            expected_directories.insert(directory.to_path_buf());
            parent = directory.parent();
        }
    }

    let mut actual_files = BTreeSet::new();
    let mut actual_directories = BTreeSet::new();
    collect_scaffold_tree(root, root, &mut actual_files, &mut actual_directories)?;
    if actual_files != expected_files || actual_directories != expected_directories {
        return Err(LaunchError::InventoryMismatch(root.to_path_buf()));
    }
    Ok(())
}

/// Run one `git` subcommand in `cwd`, returning `Ok(())` on success and
/// `LaunchError::Git(stderr)` on any non-zero exit or spawn failure. Git is
/// invoked as a closed set of subcommands, never a shell (ADR-013/ADR-053).
fn checked_git_output(cwd: &Path, args: &[&str]) -> Result<Output, LaunchError> {
    let output = Command::new("git")
        .args(args)
        .current_dir(cwd)
        .output()
        .map_err(|e| LaunchError::Git(format!("could not run `git {}`: {e}", args.join(" "))))?;
    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        return Err(LaunchError::Git(format!(
            "`git {}` failed: {}",
            args.join(" "),
            stderr.trim()
        )));
    }
    Ok(output)
}

fn git(cwd: &Path, args: &[&str]) -> Result<(), LaunchError> {
    checked_git_output(cwd, args).map(|_| ())
}

fn git_tracked_files(cwd: &Path) -> Result<Vec<String>, LaunchError> {
    let output = checked_git_output(cwd, &["ls-files", "-z"])?;
    let mut files = Vec::new();
    for path in output.stdout.split(|byte| *byte == 0) {
        if path.is_empty() {
            continue;
        }
        files.push(
            String::from_utf8(path.to_vec()).map_err(|_| {
                LaunchError::Git("git returned a non-UTF-8 tracked path".to_string())
            })?,
        );
    }
    files.sort();
    Ok(files)
}

/// Bootstrap a new project repo per `spec`. Deterministic, no LLM. See the
/// module doc for the full contract.
pub fn scaffold(spec: &LaunchSpec) -> Result<ScaffoldReport, LaunchError> {
    // 1. Refuse-to-clobber (the sole safety property).
    if !target_is_clobber_safe(&spec.path)? {
        return Err(LaunchError::TargetNotEmpty(spec.path.clone()));
    }
    // 2. Validate.
    validate_project_name(&spec.name).map_err(LaunchError::Invalid)?;
    validate_goal(&spec.goal).map_err(LaunchError::Invalid)?;
    let rust_package_name = match spec.project_type {
        ProjectType::Rust => Some(cargo_package_name(&spec.name).map_err(LaunchError::Invalid)?),
        _ => None,
    };

    // 3. Atomically reserve an absent root, revalidate an existing empty root,
    //    and exclusively create every scaffold-owned child directory.
    reserve_target(&spec.path)?;
    for directory in [
        "docs",
        "docs/intents",
        "docs/work",
        "docs/sprints",
        "docs/history",
    ] {
        create_scaffold_dir(&spec.path, directory)?;
    }

    // 4. Seed skeleton.
    let type_line = match spec.project_type {
        ProjectType::Empty => String::new(),
        _ => format!("\n\n**Type:** {:?}", spec.project_type),
    };
    let project_name = escape_markdown_text(spec.name.trim());
    let rendered_goal = render_markdown_literal(&spec.goal);
    let readme = format!("# {project_name}\n\n## Goal\n\n{rendered_goal}{type_line}\n");
    write_scaffold_file(&spec.path, "README.md", readme)?;

    let mut gitignore = String::new();
    let mut files_created = vec![
        "README.md".to_string(),
        ".gitignore".to_string(),
        "docs/.sprint-loop-book".to_string(),
        "docs/README.md".to_string(),
        "docs/SUMMARY.md".to_string(),
        "docs/intents/README.md".to_string(),
        "docs/intents/INT-0001-initial-project-goal.md".to_string(),
        "docs/work/tasks.md".to_string(),
        "docs/work/completed-tasks.md".to_string(),
        "docs/work/confidence.txt".to_string(),
        "docs/sprints/README.md".to_string(),
        "docs/history/README.md".to_string(),
    ];

    // Scaffold based on project profile
    match spec.project_type {
        ProjectType::Rust => {
            gitignore.push_str("# Rust build output.\n/target/\n\n");
            // The empty `[workspace]` is load-bearing, not boilerplate. Cargo
            // walks *upward* looking for a workspace root, so a project
            // scaffolded anywhere inside another Rust tree gets adopted by it —
            // and if that ancestor manifest is not a valid workspace, `cargo
            // build` fails while naming a file this scaffold never wrote.
            //
            // Found by launching into a scratch dir under a home directory that
            // happened to contain a stray `Cargo.toml`: the fresh project failed
            // with "no targets specified in the manifest", naming that ancestor
            // manifest — a file the user had never heard of and the scaffold had
            // never written. Declaring its own workspace stops the upward walk,
            // which is the standard idiom for a standalone nested project.
            let cargo_toml = format!(
                "[package]\nname = \"{}\"\nversion = \"0.1.0\"\nedition = \"2021\"\n\n[dependencies]\n\n[workspace]\n",
                rust_package_name
                    .as_deref()
                    .expect("Rust package name was derived during validation")
            );
            write_scaffold_file(&spec.path, "Cargo.toml", cargo_toml)?;
            files_created.push("Cargo.toml".to_string());

            create_scaffold_dir(&spec.path, "src")?;
            write_scaffold_file(
                &spec.path,
                "src/main.rs",
                "fn main() {\n    println!(\"Hello, world!\");\n}\n",
            )?;
            files_created.push("src/main.rs".to_string());
        }
        ProjectType::Python => {
            write_scaffold_file(&spec.path, "requirements.txt", "")?;
            files_created.push("requirements.txt".to_string());

            create_scaffold_dir(&spec.path, "src")?;
            write_scaffold_file(
                &spec.path,
                "src/main.py",
                "def main():\n    print(\"Hello, world!\")\n\nif __name__ == \"__main__\":\n    main()\n",
            )?;
            files_created.push("src/main.py".to_string());
            gitignore.push_str("__pycache__/\n*.pyc\n.venv/\nvenv/\n\n");
        }
        ProjectType::Web => {
            write_scaffold_file(
                &spec.path,
                "index.html",
                "<!DOCTYPE html>\n<html>\n<head>\n    <title>App</title>\n    <link rel=\"stylesheet\" href=\"style.css\">\n</head>\n<body>\n    <h1>App</h1>\n    <script src=\"app.js\"></script>\n</body>\n</html>\n",
            )?;
            files_created.push("index.html".to_string());
            write_scaffold_file(
                &spec.path,
                "style.css",
                "body {\n    font-family: sans-serif;\n}\n",
            )?;
            files_created.push("style.css".to_string());
            write_scaffold_file(&spec.path, "app.js", "console.log(\"Hello, world!\");\n")?;
            files_created.push("app.js".to_string());
        }
        ProjectType::Empty => {}
    }

    gitignore.push_str(
        "# >>> sprint-loops >>>\n# The Book is tracked. Ignore only transient helper output.\n*.tmp\n/guards-report.ndjson\n# <<< sprint-loops <<<\n",
    );
    write_scaffold_file(&spec.path, ".gitignore", gitignore)?;

    let tasks = derive_initial_tasks(&spec.goal);
    let intent_path = "../intents/INT-0001-initial-project-goal.md";
    let mut work_tasks =
        String::from("# Agent Tasks (Persistent Backlog)\n\n## Initial backlog\n\n");
    for (index, task) in tasks.iter().enumerate() {
        let task = escape_markdown_text(task);
        work_tasks.push_str(&format!(
            "- [ ] **T-{task_id:04} — {task}.** Intent: [INT-0001]({intent_path}).\n",
            task_id = index + 1,
        ));
    }
    write_scaffold_file(&spec.path, "docs/work/tasks.md", work_tasks)?;

    let work_evidence = (1..=tasks.len())
        .map(|task_id| format!("[T-{task_id:04}](../work/tasks.md)"))
        .collect::<Vec<_>>()
        .join(", ");
    let rendered_intent_goal = render_markdown_literal(&spec.goal);

    let intent = format!(
        "# INT-0001 — Initial project goal\n\n\
         <!-- sprint-loop-intent-v2 -->\n\
         - **Intent ID:** INT-0001\n\
         - **State:** planned\n\
         - **Work evidence:** {work_evidence}\n\
         - **Completion evidence:** none\n\
         - **Code evidence:** none\n\
         - **Test evidence:** none\n\
         - **Documentation evidence:** none\n\n\
         ## Intent\n\n\
         Deliver the initial project goal:\n\n\
         {rendered_intent_goal}\n\n\
         The scaffold records the supplied goal without adding unstated scope or implementation constraints.\n\n\
         ## Acceptance criteria\n\n\
         1. The project demonstrably satisfies the supplied goal.\n\
         2. Completed work is verified and recorded in the Project Book.\n\n\
         ## Rationale\n\n\
         This intent preserves the goal supplied at project launch as stable semantic authority.\n\n\
         ## Alternatives\n\n\
         No alternatives were selected at scaffold time; research should record them before implementation decisions are finalized.\n\n\
         ## Consequences\n\n\
         Initial work is represented by goal-derived tasks linked back to this intent.\n\n\
         ## Transition history\n\n\
         - Initial scaffold: created as `planned` from the launch goal.\n",
    );

    for (path, contents) in [
        ("docs/.sprint-loop-book", "schema-version: 2\n"),
        (
            "docs/README.md",
            "# Project Book\n\nThis directory is the canonical Sprint Loops Book: project intent, executable\nwork, realization evidence, and sprint provenance live here together.\n",
        ),
        (
            "docs/SUMMARY.md",
            "# Summary\n\n- [Project Book](README.md)\n- [Intents](intents/README.md)\n  - [INT-0001 — Initial project goal](intents/INT-0001-initial-project-goal.md)\n- [Tasks](work/tasks.md)\n- [Completed tasks](work/completed-tasks.md)\n- [Sprint provenance](sprints/README.md)\n- [History](history/README.md)\n",
        ),
        (
            "docs/intents/README.md",
            "# Project Intents\n\nIntent chapters are the semantic authority for desired outcomes. Each chapter records a stable `INT-NNNN` identifier, lifecycle state, evidence links, acceptance criteria, rationale, alternatives, consequences, and transition history. Legal states are `proposed`, `planned`, `active`, `deferred`, `realized`, `superseded`, and `abandoned`.\n\n## Current intents\n\n- [INT-0001 — Initial project goal](INT-0001-initial-project-goal.md)\n",
        ),
        (
            "docs/work/completed-tasks.md",
            "# Completed Tasks Log (Append-Only)\n",
        ),
        ("docs/work/confidence.txt", "1.0\n"),
        (
            "docs/sprints/README.md",
            "# Sprint Provenance\n\nEach `sN/` directory preserves the research, plans, tests, and close evidence for one sprint.\n",
        ),
        (
            "docs/history/README.md",
            "# Historical Records\n\nThis directory contains non-authoritative historical provenance. Current intent and work state live in `../intents/` and `../work/`.\n",
        ),
    ] {
        write_scaffold_file(&spec.path, path, contents)?;
    }
    write_scaffold_file(
        &spec.path,
        "docs/intents/INT-0001-initial-project-goal.md",
        intent,
    )?;

    // 5. Verify the complete reserved tree, then reserve `.git` and initialize
    //    it. Force-add only the fixed generated inventory so ambient global or
    //    system excludes cannot silently omit Book files.
    files_created.sort();
    verify_scaffold_inventory(&spec.path, &files_created)?;
    create_scaffold_dir(&spec.path, ".git")?;
    git(&spec.path, &["init"])?;
    let mut add_args = Vec::with_capacity(files_created.len() + 3);
    add_args.extend(["add", "-f", "--"]);
    add_args.extend(files_created.iter().map(String::as_str));
    git(&spec.path, &add_args)?;
    if git_tracked_files(&spec.path)? != files_created {
        return Err(LaunchError::InventoryMismatch(spec.path.clone()));
    }

    // Commit with a fixed identity so CI without global Git identity succeeds,
    // then establish the repository's two-branch contract.
    git(
        &spec.path,
        &[
            "-c",
            "user.name=Animus Launch",
            "-c",
            "user.email=launch@animus.local",
            "commit",
            "-m",
            "Initial scaffold (Animus Launch)",
        ],
    )?;
    git(&spec.path, &["branch", "-M", "main"])?;
    git(&spec.path, &["branch", "dev"])?;

    verify_scaffold_inventory(&spec.path, &files_created)?;
    if git_tracked_files(&spec.path)? != files_created {
        return Err(LaunchError::InventoryMismatch(spec.path.clone()));
    }

    Ok(ScaffoldReport {
        path: spec.path.clone(),
        branches: vec!["main".to_string(), "dev".to_string()],
        files_created,
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn validate_project_name_rejects_empty() {
        assert!(validate_project_name("").is_err());
        assert!(validate_project_name("   ").is_err());
        assert!(validate_project_name("demo").is_ok());
    }

    #[test]
    fn validate_project_name_rejects_control_characters_but_accepts_unicode() {
        for invalid in ["bad\nname", "bad\rname", "bad\tname", "bad\0name"] {
            assert!(
                validate_project_name(invalid).is_err(),
                "accepted {invalid:?}"
            );
        }
        assert!(validate_project_name("Ferríc 🦀").is_ok());
    }

    #[test]
    fn validate_goal_rejects_empty() {
        assert!(validate_goal("").is_err());
        assert!(validate_goal("\t\n ").is_err());
        assert!(validate_goal("build a thing").is_ok());
    }

    #[test]
    fn cargo_package_names_are_deterministic_and_toml_safe() {
        assert_eq!(cargo_package_name("My Safe-App").unwrap(), "my_safe-app");
        assert_eq!(
            cargo_package_name("123 tools").unwrap(),
            "project_123_tools"
        );
        for valid in ["dependency", "build-tool", "com0", "com10", "lpt10"] {
            assert!(cargo_package_name(valid).is_ok(), "rejected {valid:?}");
        }
        for invalid in ["quoted\"name", "crab 🦀", "path/name", "---"] {
            assert!(cargo_package_name(invalid).is_err(), "accepted {invalid:?}");
        }
    }

    #[test]
    fn cargo_package_names_reject_reserved_implicit_binary_targets() {
        for reserved in [
            "deps",
            "examples",
            "build",
            "incremental",
            "con",
            "prn",
            "aux",
            "nul",
            "com1",
            "com2",
            "com3",
            "com4",
            "com5",
            "com6",
            "com7",
            "com8",
            "com9",
            "lpt1",
            "lpt2",
            "lpt3",
            "lpt4",
            "lpt5",
            "lpt6",
            "lpt7",
            "lpt8",
            "lpt9",
        ] {
            assert!(
                cargo_package_name(reserved).is_err(),
                "accepted Cargo-reserved target {reserved:?}"
            );
        }
        assert!(
            cargo_package_name("DePs").is_err(),
            "normalization must not bypass the reserved-name check"
        );
    }

    #[test]
    fn derive_initial_tasks_nonempty() {
        let tasks = derive_initial_tasks("build a parser; add tests, then document it");
        assert!(!tasks.is_empty());
        // Each clause becomes a task referencing the goal's content.
        assert!(tasks.iter().any(|t| t.contains("parser")));
        assert!(tasks.iter().any(|t| t.contains("tests")));
        assert!(tasks.iter().any(|t| t.contains("document")));
        // A separator-free goal still yields one task.
        let single = derive_initial_tasks("a tiny CLI");
        assert_eq!(single.len(), 1);
        assert!(single[0].contains("tiny CLI"));

        let normalized = derive_initial_tasks("ship café\r\nadd 🦀 tests\rpublish docs");
        assert_eq!(normalized, ["Ship café", "Add 🦀 tests", "Publish docs"]);
    }

    #[test]
    fn target_clobber_safety_rules() {
        let dir = tempfile::tempdir().unwrap();
        // Absent path → safe.
        assert!(target_is_clobber_safe(&dir.path().join("new")).unwrap());
        // Empty dir → safe.
        let empty = dir.path().join("empty");
        std::fs::create_dir(&empty).unwrap();
        assert!(target_is_clobber_safe(&empty).unwrap());
        // Dir with a hidden-only entry → NOT safe.
        let hidden = dir.path().join("hidden");
        std::fs::create_dir(&hidden).unwrap();
        std::fs::write(hidden.join(".keep"), "x").unwrap();
        assert!(!target_is_clobber_safe(&hidden).unwrap());
        // Existing FILE → NOT safe.
        let file = dir.path().join("file");
        std::fs::write(&file, "x").unwrap();
        assert!(!target_is_clobber_safe(&file).unwrap());
    }

    #[test]
    fn exclusive_file_creation_refuses_a_racing_destination() {
        let dir = tempfile::tempdir().unwrap();
        let target = dir.path().join("project");
        reserve_target(&target).unwrap();

        // Simulate another writer winning the destination after reservation.
        std::fs::write(target.join("README.md"), "theirs").unwrap();
        let error = write_scaffold_file(&target, "README.md", "ours").unwrap_err();
        assert!(matches!(error, LaunchError::TargetNotEmpty(_)));
        assert_eq!(
            std::fs::read_to_string(target.join("README.md")).unwrap(),
            "theirs"
        );
    }

    #[test]
    fn inventory_verification_rejects_unexpected_concurrent_content() {
        let dir = tempfile::tempdir().unwrap();
        let target = dir.path().join("project");
        reserve_target(&target).unwrap();
        write_scaffold_file(&target, "README.md", "owned").unwrap();
        std::fs::write(target.join("unexpected.txt"), "theirs").unwrap();

        assert!(matches!(
            verify_scaffold_inventory(&target, &["README.md".to_string()]),
            Err(LaunchError::InventoryMismatch(_))
        ));
    }

    /// A scaffolded Rust project must declare its own workspace.
    ///
    /// Cargo resolves the workspace root by walking **up** the directory tree,
    /// so without this a fresh project nested anywhere inside another Rust tree
    /// is silently adopted by it — and when that ancestor is not a valid
    /// workspace, `cargo build` fails citing a manifest the user never wrote.
    /// Observed live: launching under a home directory that contains a stray
    /// `Cargo.toml` produced a project that would not compile.
    ///
    /// The assertion is on the emitted manifest rather than on a `cargo build`,
    /// so it holds regardless of what happens to sit above the test's tempdir.
    #[test]
    fn a_scaffolded_rust_project_declares_its_own_workspace() {
        let dir = tempfile::tempdir().expect("tempdir");
        let path = dir.path().join("proj");
        let spec = LaunchSpec {
            name: "proj".to_string(),
            path: path.clone(),
            goal: "verify the scaffold".to_string(),
            project_type: ProjectType::Rust,
        };
        scaffold(&spec).expect("scaffold must succeed");

        let manifest = std::fs::read_to_string(path.join("Cargo.toml")).expect("Cargo.toml");
        assert!(
            manifest.contains("[workspace]"),
            "a standalone scaffold must stop cargo's upward workspace search:
{manifest}"
        );
        assert!(
            path.join("src/main.rs").is_file(),
            "the manifest promises a binary target, so src/main.rs must exist"
        );
    }
}
